const INTERNAL_SERVER_ERROR = "Internal server error"
const HTTP_OK = 200
const HTTP_BAD_REQUEST = 400
const HTTP_INTERNAL_SERVER_ERROR = 500

module.exports = {
  INTERNAL_SERVER_ERROR,
  HTTP_OK,
  HTTP_BAD_REQUEST,
  HTTP_INTERNAL_SERVER_ERROR,
}
